### ISSUE TITLE
"_isMounted" is not on latest release (0.2.1)

### ISSUE THREAD

**Issue by andresmatasuarez** [leozdgao/react-script-loader#10]
I came across the same bug that was reported on this issue: https://github.com/leozdgao/react-async-script-loader/issues/7

however, I am not seeing the changes that fix that issue on the release installed on my project (which is 0.2.1 according to its own `package.json`). If I browse to `my_project_dir/node_modules/react-async-script-loader/lib/index.js` and search for `isMounted` string, it finds nothing. I look at the code for the `ScriptLoader` `componentDidMount` function and effectively there is no `isMounted` handling.

Can you confirm this? Is there anything I can do to help you get this released ASAP?

Keep up the good work :)

**Comment by leozdgao** [comment]
@andresmatasuarez 0.2.2 Released.

**Comment by andresmatasuarez** [comment]
thanks!

**Comment by dbackeus** [comment]
Maybe close the issue if it's closed?
