### ISSUE TITLE
props in componentDidMount are both false?

### ISSUE THREAD

**Issue by d30jeff** [leozdgao/react-script-loader#27]
Could someone explain to my what's happening in the example?

```
componentWillReceiveProps(nextProps) {
    const { isScriptLoaded, isScriptLoadSucceed } = nextProps

    if (isScriptLoaded && isScriptLoadSucceed) {
      // Do stuff
    }
  }

  componentDidMount() {
    const { isScriptLoaded, isScriptLoadSucceed } = this.props
    console.log(isScriptLoaded, isScriptLoadSucceed) // false false
  }
```

I don't understand why 
`console.log(isScriptLoaded, isScriptLoadSucceed)` are returning false whereas the props in **CWRP** are both true. 

I mean when the lifecycle hit **CWM** shouldn't they both be true as well?

Thanks

**Comment by orion110217** [comment]
The scripts are async, it might not be ready even after componentDidMount, that's why this module is created.
