### ISSUE TITLE
Issue with Script Loader calling setState on an unmounted component

### ISSUE THREAD

**Issue by struckm** [leozdgao/react-script-loader#7]
When my component unmounts prior to the ScriptLoader finishing loading the scripts I get the following error: 

"setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component."

The ScriptLoader should be listening for componentWillUnmount and not call the setState.

**Comment by leozdgao** [comment]
Merged, thanks for your contibution.
